-- Migration: Criar tabela base_tudobelo_para_testes (cópia isolada da base_tudobelo_intermediaria)

create table public.base_tudobelo_para_testes (
  id text not null,
  selection boolean null default false,
  documento text null,
  tipo_documento text null,
  serie_documento text null,
  codigo_parceiro text null,
  nome_parceiro text null,
  cnpj_cpf text null,
  numero_parcela text null,
  valor_parcela numeric null,
  saldo_parcela numeric null,
  data_documento date null,
  data_vencimento date null,
  dias_atraso text null,
  observacoes text null,
  forma_pagamento text null,
  status_boleto text null,
  filial text null,
  vendedor text null,
  uf_cobranca text null,
  municipio_cobranca text null,
  inserido_cedrus boolean null default false,
  id_titulo_cedrus text null,
  credor_cedrus text null,
  data_criacao timestamp with time zone null default now(),
  ultima_atualizacao timestamp with time zone null default now(),
  processado_internamente boolean null,
  status_titulo text null,
  status_cedrus text null,
  etapa text null,
  tipo_titulo text null,
  id_negociacao_cedrus text null,
  linha_digitavel text null,
  data_pagamento date null,
  valor_pago numeric null,
  nome_fantasia text null,
  fone1 text null,
  fone2 text null,
  email text null,
  endereco text null,
  numero_endereco text null,
  complemento text null,
  bairro text null,
  cidade text null,
  uf text null,
  tipo_negocio text null,
  cod_devedor_cedrus text null,
  negativado boolean null default false,
  email_inicial_enviado boolean null default false,
  bloqueado boolean null default false,
  constraint base_tudobelo_para_testes_pkey primary key (id)
) TABLESPACE pg_default;

create index if not exists base_tudobelo_para_testes_status_titulo_idx on public.base_tudobelo_para_testes using btree (status_titulo) TABLESPACE pg_default;
create index if not exists base_tudobelo_para_testes_status_cedrus_idx on public.base_tudobelo_para_testes using btree (status_cedrus) TABLESPACE pg_default;
create index if not exists base_tudobelo_para_testes_etapa_idx on public.base_tudobelo_para_testes using btree (etapa) TABLESPACE pg_default;
