-- Tabela para armazenar log de alterações dos títulos Tudo Belo
-- Registra cada alteração de forma fiel, mesmo que feita manualmente via sistemas externos

CREATE TABLE IF NOT EXISTS public.base_tudobelo_log_alteracoes (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  
  -- Referência ao título alterado
  titulo_id text not null,
  
  -- Informações sobre a alteração
  campo_alterado text not null,
  valor_anterior text null,
  valor_novo text null,
  
  -- Origem da alteração
  origem text not null default 'sistema_interno', -- Ex: 'sistema_interno', 'manual_externo', 'api', 'importacao'
  
  -- Usuário que fez a alteração (quando disponível)
  usuario_id text null,
  usuario_email text null,
  
  -- Metadados adicionais
  descricao text null,
  metadata jsonb null,
  
  constraint base_tudobelo_log_alteracoes_pkey primary key (id)
) TABLESPACE pg_default;

-- Índices para consultas frequentes
CREATE INDEX IF NOT EXISTS idx_log_alteracoes_titulo_id ON public.base_tudobelo_log_alteracoes(titulo_id);
CREATE INDEX IF NOT EXISTS idx_log_alteracoes_created_at ON public.base_tudobelo_log_alteracoes(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_log_alteracoes_campo ON public.base_tudobelo_log_alteracoes(campo_alterado);
CREATE INDEX IF NOT EXISTS idx_log_alteracoes_origem ON public.base_tudobelo_log_alteracoes(origem);

-- Comentários para documentação
COMMENT ON TABLE public.base_tudobelo_log_alteracoes IS 'Log de alterações dos títulos Tudo Belo - registra cada mudança de forma fiel';
COMMENT ON COLUMN public.base_tudobelo_log_alteracoes.titulo_id IS 'ID do título na tabela base_tudobelo_intermediaria';
COMMENT ON COLUMN public.base_tudobelo_log_alteracoes.campo_alterado IS 'Nome do campo que foi alterado';
COMMENT ON COLUMN public.base_tudobelo_log_alteracoes.valor_anterior IS 'Valor antes da alteração (serializado como texto)';
COMMENT ON COLUMN public.base_tudobelo_log_alteracoes.valor_novo IS 'Valor depois da alteração (serializado como texto)';
COMMENT ON COLUMN public.base_tudobelo_log_alteracoes.origem IS 'Origem da alteração: sistema_interno, manual_externo, api, importacao';
COMMENT ON COLUMN public.base_tudobelo_log_alteracoes.usuario_id IS 'ID do usuário que fez a alteração (quando disponível)';
COMMENT ON COLUMN public.base_tudobelo_log_alteracoes.usuario_email IS 'Email do usuário que fez a alteração (quando disponível)';
COMMENT ON COLUMN public.base_tudobelo_log_alteracoes.metadata IS 'Dados adicionais em formato JSON';
